### ISSUE TITLE
Sign Up Button does not work after modifying.

### ISSUE THREAD

**Issue by zhang295** [zhang295/csc444#2]

**Comment by zhang295** [comment]
Cannot create account after modifying the sign_up page.

**Comment by TonyZT132** [comment]
I'm fixing that now

**Comment by TonyZT132** [comment]
I've removed "birth" in sign up permit. Now the sign up works. I will create new issue for whether adding the "birth" in sign  up page.

**Comment by TonyZT132** [comment]
Sign up button won't work when direct from home page. Also, the layout will mess up after multiple submits

**Comment by TonyZT132** [comment]
This is not loaded if use link from nav bar:
ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"

**Comment by TonyZT132** [comment]
It should work now. I will keep this issue open for some days and then close.

**Comment by angelwu0409** [comment]
sign up button is not working again, 200 OK returned to sever after signup button is clicked, but user still stay on the same page

**Comment by TonyZT132** [comment]
Please check the sign up and login now; if everything works, close this issue
