### ISSUE TITLE
With the Devise module, regular expression validation not enabled for Log in

### ISSUE THREAD

**Issue by MrVJPman** [zhang295/csc444#8]
I looked over the entire code, and it appears the team is using the Devise module to set up a lot of the basic login. 

I searched up on google and there doesn't seem to be any instructions to validate email during login only (as long as the Devise module is in use), most of them are for new-user-creation.

I believe to setup the login with email/password, regex, it needs to be done in the file

<code>app/views/devise/sessions/new.html.erb</code>

After examining the contents of this file, I believe an instance variable is needed to communicate from the controller to this view page, where the instance variable is carrying the contents of the regular communication. The line of code that does this appear to be

<code>    <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => {:class => 'login'}) do |f| %> </code> 

I did further research and it appears this is a part of the Devise module.

**Comment by TonyZT132** [comment]
I think the email regex should already be configured in config/initializer/devise.rb
